package org.example.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DbUtils {

    public static Connection getDbConnection() throws SQLException {
        String DB_URL = "jdbc:postgresql://localhost:5432/meals_db";
        String USER = "postgres";
        String PASS = "1111";
        return DriverManager.getConnection(DB_URL, USER, PASS);
    }

    public static void checkDbTableStructure(Connection dbConnection) {
        String createMealsTable = "CREATE TABLE IF NOT EXISTS meals (" +
                "meal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "category VARCHAR(255), " +
                "meal VARCHAR(255)" +
                ");";

        String createIngredientsTable = "CREATE TABLE IF NOT EXISTS ingredients (" +
                "ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "ingredient VARCHAR(255), " +
                "meal_id INTEGER, " +
                "FOREIGN KEY (meal_id) REFERENCES meals(meal_id) ON DELETE CASCADE" +
                ");";

        try (Statement statement = dbConnection.createStatement()) {
            statement.executeUpdate(createMealsTable);
            statement.executeUpdate(createIngredientsTable);
        } catch (SQLException e) {
            System.err.println("Error occurred while creating tables: " + e.getMessage());
        }
    }
}
